import type { ExerciseInstruction } from './types'

// Concise, useful instruction content for the exercises, drills, stretches,
// and swim work in Daniel's plan. Matched by a normalized key derived from
// the item name. Kept brief by default; UI expands "More detail" sections.

function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
}

export const instructions: ExerciseInstruction[] = [
  {
    key: 'open tuck planche holds',
    title: 'Open Tuck Planche Holds',
    summary: 'Straight-arm lean with hips opened past 90 degrees, knees tucked.',
    setup: 'Hands on parallettes or floor, shoulders stacked over hands, fingers gripping.',
    howTo: [
      'Lean forward until shoulders pass in front of the wrists.',
      'Protract hard (push the floor away) and posterior-tilt the pelvis.',
      'Open the hips a little past 90 degrees while keeping knees tucked.',
      'Hold for quality time, then rest fully between sets.',
    ],
    cues: ['Push the floor away', 'Open the hips, not the knees', 'Lean, do not pike'],
    commonMistake: 'Reverting to a closed tuck under fatigue and losing protraction.',
    easier: 'Closed tuck planche, or reduce the lean slightly.',
    harder: 'Advanced tuck or add a 1-2s longer target hold.',
    feelsLike: 'Hard work in the front delts and the long head of biceps; locked elbows.',
    discomfortWarning: 'Stop the set if forearm pain exceeds 2/5. Do not train through wrist pain.',
    whyInPlan: 'Your primary planche stage right now — building repeatable 10-12s holds.',
    guideUrl: 'https://example.com/guides/planche',
  },
  {
    key: 'advanced tuck negatives',
    title: 'Advanced Tuck Negatives',
    summary: 'Slow lowering into the advanced tuck position to build the next stage.',
    setup: 'Start in a solid tuck planche, protracted and posterior-tilted.',
    howTo: [
      'Begin in a tuck planche with hips at shoulder height.',
      'Slowly open the hip angle, sliding toward advanced tuck.',
      'Resist gravity on the way down for the target seconds.',
      'Reset and repeat with full rest.',
    ],
    cues: ['Open the hips gradually', 'Keep the back flat', 'Stay protracted'],
    commonMistake: 'Rounding the upper back instead of opening from the hips.',
    easier: 'Shorter negatives (2-3s) or stay in tuck.',
    harder: 'Advanced tuck holds (isometric) instead of negatives.',
    feelsLike: 'Intense straight-arm tension; the lever gets harder as hips open.',
    discomfortWarning: 'Back off if forearm or wrist discomfort climbs above 2/5.',
    whyInPlan: 'Bridges your open tuck to the advanced tuck stage.',
  },
  {
    key: 'freestanding kick up practice',
    title: 'Freestanding Kick-up Practice',
    summary: 'Reliable entries into a freestanding handstand.',
    setup: 'Open floor space, hands shoulder-width, eyes between the hands.',
    howTo: [
      'Place hands down with a slight bend, lead leg up.',
      'Kick the trailing leg and stack hips over shoulders.',
      'Aim to float into balance rather than crashing past it.',
      'Bail safely to a cartwheel if you overshoot.',
    ],
    cues: ['Hips over shoulders', 'Commit, do not float timid', 'Spread the fingers and grip'],
    commonMistake: 'Under-kicking out of caution or over-kicking past balance.',
    easier: 'Wall kick-ups to find the balance point.',
    harder: 'Add a hold target after each successful entry.',
    feelsLike: 'A brief moment of weightlessness when you find the stack.',
    whyInPlan: 'Kick-up consistency is your current handstand limiter (~3/10).',
    guideUrl: 'https://example.com/guides/handstand',
  },
  {
    key: 'wall handstand line drills',
    title: 'Wall Handstand Line Drills',
    summary: 'Build a straight, stacked handstand line against the wall.',
    setup: 'Chest-to-wall, hands a hand-span from the baseboard.',
    howTo: [
      'Walk up the wall into a chest-to-wall handstand.',
      'Posterior-tilt the pelvis and push tall through the shoulders.',
      'Squeeze legs together, point toes, ribs down.',
      'Hold the line and breathe.',
    ],
    cues: ['Push tall', 'Ribs down', 'Posterior pelvic tilt'],
    commonMistake: 'Arching the lower back and flaring the ribs.',
    easier: 'Shorter holds or back-to-wall.',
    harder: 'Toe-pulls off the wall toward freestanding balance.',
    feelsLike: 'Active, tall shoulders and a long straight body.',
    whyInPlan: 'Reinforces the straight line your freestanding work needs.',
  },
  {
    key: 'seated pike compression lifts',
    title: 'Seated Pike Compression Lifts',
    summary: 'Active compression strength for the press-to-handstand.',
    setup: 'Seated, legs straight in front, hands by the hips.',
    howTo: [
      'Sit tall with straight legs and pointed toes.',
      'Actively lift the heels off the floor by compressing.',
      'Hold briefly at the top, lower with control.',
    ],
    cues: ['Lift the heels actively', 'No rounding', 'Pull the thighs to the chest'],
    commonMistake: 'Rounding the back to fake height instead of compressing.',
    easier: 'Lift one leg at a time.',
    harder: 'Elevate the hands or add ankle weight.',
    feelsLike: 'Hip flexors and lower abs working hard with straight knees.',
    whyInPlan: 'Active compression is the main requirement for your press goal.',
  },
  {
    key: 'straight arm scap prep',
    title: 'Straight-arm Scap Prep',
    summary: 'Warm up scapular protraction with locked elbows.',
    setup: 'Support position on parallettes or floor.',
    howTo: [
      'Lock the elbows fully.',
      'Protract (push up and apart) then relax between reps.',
      'Move slowly with control.',
    ],
    cues: ['Elbows locked', 'Full protraction', 'Slow tempo'],
    commonMistake: 'Bending the elbows to cheat the range.',
    easier: 'Do it on an incline or kneeling.',
    harder: 'Add a pause at full protraction.',
    feelsLike: 'Serratus and shoulders switching on; a good pre-planche primer.',
    whyInPlan: 'Primes the straight-arm strength your planche work demands.',
  },
  {
    key: 'l sit hold',
    title: 'L-sit Hold',
    summary: 'Compression and straight-arm support strength.',
    setup: 'Hands on parallettes or floor, legs straight in front.',
    howTo: [
      'Depress the shoulders and lock the elbows.',
      'Lift the legs to horizontal, point the toes.',
      'Hold for max quality time.',
    ],
    cues: ['Depress the shoulders', 'Point the toes', 'Legs straight'],
    commonMistake: 'Bending the knees or shrugging the shoulders.',
    easier: 'Tuck L-sit or one-leg L-sit.',
    harder: 'Raise toward a V-sit.',
    feelsLike: 'Strong compression in the hip flexors and abs.',
    whyInPlan: 'Supports compression for both planche and press work.',
  },
  {
    key: 'wrist decompression flow',
    title: 'Wrist Decompression Flow',
    summary: 'Gentle mobility to relieve forearm and wrist tension.',
    setup: 'Kneeling or seated with hands on the floor.',
    howTo: [
      'Move slowly through wrist flexion and extension.',
      'Add gentle forearm massage where it feels tight.',
      'Keep everything pain-free.',
    ],
    cues: ['Slow and gentle', 'No sharp pain', 'Breathe and relax'],
    commonMistake: 'Forcing range when the forearm is already irritated.',
    easier: 'Reduce range and pressure.',
    harder: 'Add light loaded rocks once pain-free.',
    feelsLike: 'Relief and circulation, not a stretch you fight.',
    discomfortWarning: 'This is recovery work — stop if it sharpens any pain.',
    whyInPlan: 'Manages the forearm discomfort you have been monitoring.',
  },
  {
    key: 'swim lesson',
    title: 'Swim Lesson',
    summary: 'Coached freestyle technique session.',
    setup: 'Pool, lesson time 3:30-4:20 PM.',
    howTo: [
      'Warm up easy, then work the technique focus for the day.',
      'Prioritize body position and breathing rhythm over speed.',
      'Finish with a relaxed cooldown.',
    ],
    cues: ['Long body line', 'Exhale underwater', 'Smooth catch'],
    commonMistake: 'Lifting the head to breathe and sinking the hips.',
    easier: 'More rest between lengths.',
    harder: 'Add short pace intervals at the end.',
    feelsLike: 'Easy, technique-focused effort — low-impact cross-training.',
    whyInPlan: 'Consistent Tue/Thu lessons build your swimming skill and cardio.',
    guideUrl: 'https://example.com/guides/swimming',
  },
  {
    key: 'box press negatives',
    title: 'Box Press Negatives',
    summary: 'Eccentric lowering from handstand toward a box for press strength.',
    setup: 'Handstand near a box, straddle ready.',
    howTo: [
      'From a handstand, slowly lower with a wide straddle.',
      'Lead with the hips, keeping shoulders forward.',
      'Touch down to the box with control.',
    ],
    cues: ['Hips lead', 'Straddle wide', 'Slow lower'],
    commonMistake: 'Dropping shoulders before lifting the hips.',
    easier: 'Higher box or shorter range.',
    harder: 'Lower box or pause mid-range.',
    feelsLike: 'Compression and shoulder strength fighting the descent.',
    whyInPlan: 'Trains the eccentric strength your press pathway needs.',
    guideUrl: 'https://example.com/guides/press',
  },
  // --- Flexibility / mobility drills ---
  {
    key: 'active pike lifts',
    title: 'Active Pike Lifts',
    summary: 'Active compression for the pike and press.',
    setup: 'Seated, legs straight, hands by hips.',
    howTo: ['Lift the heels actively off the floor.', 'Hold briefly, lower with control.'],
    cues: ['Lift heels actively', 'No rounding'],
    commonMistake: 'Rounding the back instead of compressing the hips.',
    easier: 'One leg at a time.',
    harder: 'Elevate the hands.',
    feelsLike: 'Active hip flexor work with straight knees.',
    whyInPlan: 'Active compression for your press goal.',
  },
  {
    key: 'pancake good mornings',
    title: 'Pancake Good Mornings',
    summary: 'Straddle range with a flat back for planche and press.',
    setup: 'Seated in a wide straddle.',
    howTo: ['Hinge forward from the hips.', 'Keep the back flat as you reach.', 'Return tall.'],
    cues: ['Hinge from hips', 'Flat back'],
    commonMistake: 'Rounding the spine to reach further.',
    easier: 'Narrow the straddle or sit on a cushion.',
    harder: 'Increase the forward reach and pause.',
    feelsLike: 'A strong stretch through the inner thighs and hamstrings.',
    whyInPlan: 'Builds straddle range supporting planche and press.',
  },
  {
    key: 'wall slides dowel',
    title: 'Wall Slides + Dowel',
    summary: 'Shoulder flexion for a clean handstand line.',
    setup: 'Back to wall, ribs down, dowel overhead.',
    howTo: ['Reach overhead keeping ribs down.', 'Slide up to full flexion without arching.'],
    cues: ['Ribs down', 'Reach overhead'],
    commonMistake: 'Arching the back to fake overhead range.',
    easier: 'Reduce the overhead range.',
    harder: 'Move closer to the wall.',
    feelsLike: 'A working stretch in the lats and shoulders.',
    discomfortWarning: 'Stop if the shoulder pinches given your injury history.',
    whyInPlan: 'Improves the overhead line your handstand needs.',
  },
  {
    key: 'loaded wrist rocks',
    title: 'Loaded Wrist Rocks',
    summary: 'Build wrist tolerance for planche loading.',
    setup: 'Hands on the floor, fingers forward.',
    howTo: ['Rock slowly forward and back over the wrists.', 'Keep it controlled and pain-free.'],
    cues: ['Slow', 'Controlled', 'Pain-free'],
    commonMistake: 'Loading too fast into an irritated forearm.',
    easier: 'Reduce the lean and pressure.',
    harder: 'Add bodyweight gradually.',
    feelsLike: 'A gentle stretch and warm-up through the wrists.',
    discomfortWarning: 'Avoid if forearm pain is above 2/5.',
    whyInPlan: 'Prepares the wrists for planche load while you monitor the forearm.',
  },
  {
    key: 'couch stretch',
    title: 'Couch Stretch',
    summary: 'Hip flexor and quad length to counter sitting.',
    setup: 'Rear foot elevated against a wall or couch, front foot planted.',
    howTo: ['Tuck the pelvis under.', 'Stay tall through the torso.', 'Hold each side.'],
    cues: ['Posterior tilt', 'Tall torso'],
    commonMistake: 'Arching the back instead of tucking the pelvis.',
    easier: 'Lower the rear knee elevation.',
    harder: 'Raise the rear knee higher.',
    feelsLike: 'A deep stretch across the front of the hip and thigh.',
    whyInPlan: 'Counters long sitting and supports your overhead line.',
  },
  {
    key: 'seated compression holds',
    title: 'Seated Compression Holds',
    summary: 'The core requirement for press-to-handstand.',
    setup: 'Seated, legs straight, hands lifting.',
    howTo: ['Lift the hands and pull the legs toward the chest.', 'Keep legs straight throughout.'],
    cues: ['Hands lift', 'Legs stay straight'],
    commonMistake: 'Bending the knees to gain height.',
    easier: 'Hold for shorter time.',
    harder: 'Lift the hips off the floor.',
    feelsLike: 'Maximal active compression with straight knees.',
    whyInPlan: 'Directly trains the compression the press requires.',
  },
]

const byKey = new Map(instructions.map((i) => [i.key, i]))

export function findInstruction(name: string): ExerciseInstruction | undefined {
  const n = norm(name)
  if (byKey.has(n)) return byKey.get(n)
  // Loose contains-match so plan names and workout names both resolve.
  for (const inst of instructions) {
    if (n.includes(inst.key) || inst.key.includes(n)) return inst
  }
  return undefined
}
